# Generated by Django 3.1.1 on 2020-09-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartidoPolitico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='partidos')),
                ('nombre', models.CharField(max_length=60)),
                ('Abreviatura', models.CharField(max_length=60)),
                ('numero', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Partidos Politicos',
            },
        ),
    ]
