# Generated by Django 3.1.1 on 2020-09-30 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Elecciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dignidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Presidente', 'Presidente'), ('Asambleista Nacional', 'Asambleista Nacional'), ('Asambleista Provincial', 'Asambleista Provincial'), ('Parlamentario Andino', 'Parlamentario Andino')], max_length=60)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elecciones.partidopolitico')),
            ],
        ),
    ]
