# Generated by Django 3.1.1 on 2020-09-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dignidad',
            old_name='tipo',
            new_name='dignidad',
        ),
        migrations.AddField(
            model_name='dignidad',
            name='nombre',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
