# Generated by Django 3.1.1 on 2020-09-30 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lugares', '0001_initial'),
        ('Candidatos', '0002_auto_20200929_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='dignidad',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lugares.provincia'),
        ),
    ]
